/**
 * AgriProfit — Curated Crop Agronomic & Economic Catalog
 * =======================================================
 * Sourced from ICAR package of practices, CACP Price Policy reports (2024-25),
 * and Agmarknet mandi benchmarks.
 */

export type CropCategory = "Cereal" | "Pulse" | "Oilseed" | "Cash Crop" | "Vegetable" | "Spice" | "Fruit";
export type CropSeason = "Kharif" | "Rabi" | "Zaid" | "Perennial";

export type CropRecord = {
  id: string;
  slug: string;
  name: string;
  hindiName: string;
  category: CropCategory;
  season: CropSeason;
  durationDays: number;
  waterRequirementMm: number;
  waterLevel: "Low" | "Medium" | "High";
  suitableSoils: string[];
  tempRange: { min: number; max: number; idealMin: number; idealMax: number };
  rainfallMm: { min: number; max: number; optimal: number };
  yield: { kgPerHa: number; quintalsPerAcre: number };
  costs: {
    seed: number;
    fertilizer: number;
    labor: number;
    irrigation: number;
    other: number;
    totalPerAcre: number;
    totalPerHa: number;
  };
  economics: {
    typicalPricePerQuintal: number;
    mspPricePerQuintal: number | null;
    mspEligible: boolean;
    expectedGrossRevenuePerAcre: number;
    expectedNetProfitPerAcre: number;
    roi: number;
  };
  riskFactors: string[];
  pestsAndDiseases: string[];
  provenance: {
    sourceType: "official" | "estimated";
    benchmarkSource: string;
    lastUpdated: string;
  };
};

export const CROP_DATABASE: CropRecord[] = [
  {
    id: "CROP002",
    slug: "wheat",
    name: "Wheat (Gehun)",
    hindiName: "गेहूं",
    category: "Cereal",
    season: "Rabi",
    durationDays: 130,
    waterRequirementMm: 450,
    waterLevel: "Medium",
    suitableSoils: ["Loam", "Clay loam", "Alluvial"],
    tempRange: { min: 4, max: 32, idealMin: 15, idealMax: 25 },
    rainfallMm: { min: 350, max: 750, optimal: 500 },
    yield: { kgPerHa: 3600, quintalsPerAcre: 14.5 },
    costs: {
      seed: 1700,
      fertilizer: 3000,
      labor: 4000,
      irrigation: 1800,
      other: 1000,
      totalPerAcre: 11500,
      totalPerHa: 28700,
    },
    economics: {
      typicalPricePerQuintal: 2380,
      mspPricePerQuintal: 2275,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 34510,
      expectedNetProfitPerAcre: 23010,
      roi: 2.0,
    },
    riskFactors: ["Terminal heat stress in February/March", "Lodging during untimely rain", "Yellow rust epidemic"],
    pestsAndDiseases: ["Yellow / Stripe Rust (Puccinia striiformis)", "Karnal Bunt", "Aphids (Mahun)"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IIWBR Karnal / CACP Rabi MSP 2024-25",
      lastUpdated: "2024-10-15",
    },
  },
  {
    id: "CROP013",
    slug: "mustard",
    name: "Mustard (Sarson)",
    hindiName: "सरसों",
    category: "Oilseed",
    season: "Rabi",
    durationDays: 120,
    waterRequirementMm: 350,
    waterLevel: "Low",
    suitableSoils: ["Loam", "Sandy loam", "Alluvial"],
    tempRange: { min: 5, max: 30, idealMin: 15, idealMax: 25 },
    rainfallMm: { min: 250, max: 500, optimal: 350 },
    yield: { kgPerHa: 1500, quintalsPerAcre: 6.1 },
    costs: {
      seed: 900,
      fertilizer: 1600,
      labor: 2800,
      irrigation: 1000,
      other: 600,
      totalPerAcre: 6900,
      totalPerHa: 17200,
    },
    economics: {
      typicalPricePerQuintal: 5650,
      mspPricePerQuintal: 5650,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 34465,
      expectedNetProfitPerAcre: 27565,
      roi: 3.0,
    },
    riskFactors: ["Aphid attack during flowering", "Frost damage during pod formation", "Sclerotinia stem rot"],
    pestsAndDiseases: ["Mustard Aphid (Lipaphis erysimi)", "White Rust (Albugo candida)", "Alternaria Blight"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-DRMR Bharatpur / CACP 2024-25",
      lastUpdated: "2024-10-15",
    },
  },
  {
    id: "CROP007",
    slug: "chickpea",
    name: "Chickpea / Gram (Chana)",
    hindiName: "चना",
    category: "Pulse",
    season: "Rabi",
    durationDays: 100,
    waterRequirementMm: 350,
    waterLevel: "Low",
    suitableSoils: ["Sandy loam", "Loam", "Black soil"],
    tempRange: { min: 10, max: 30, idealMin: 18, idealMax: 25 },
    rainfallMm: { min: 250, max: 500, optimal: 350 },
    yield: { kgPerHa: 1200, quintalsPerAcre: 4.8 },
    costs: {
      seed: 1400,
      fertilizer: 1600,
      labor: 3200,
      irrigation: 800,
      other: 600,
      totalPerAcre: 7600,
      totalPerHa: 19000,
    },
    economics: {
      typicalPricePerQuintal: 5440,
      mspPricePerQuintal: 5440,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 26112,
      expectedNetProfitPerAcre: 18512,
      roi: 2.43,
    },
    riskFactors: ["Pod borer (Helicoverpa)", "Waterlogging (highly sensitive)", "Fusarium wilt"],
    pestsAndDiseases: ["Gram Pod Borer (Helicoverpa armigera)", "Fusarium Wilt", "Ascochyta Blight"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IIPR Kanpur / CACP 2024-25",
      lastUpdated: "2024-10-15",
    },
  },
  {
    id: "CROP003",
    slug: "maize",
    name: "Maize (Makka)",
    hindiName: "मक्का",
    category: "Cereal",
    season: "Kharif",
    durationDays: 100,
    waterRequirementMm: 550,
    waterLevel: "Medium",
    suitableSoils: ["Loam", "Alluvial", "Red loam"],
    tempRange: { min: 10, max: 35, idealMin: 21, idealMax: 27 },
    rainfallMm: { min: 450, max: 900, optimal: 600 },
    yield: { kgPerHa: 3200, quintalsPerAcre: 13.0 },
    costs: {
      seed: 1500,
      fertilizer: 2600,
      labor: 3600,
      irrigation: 1400,
      other: 900,
      totalPerAcre: 10000,
      totalPerHa: 25000,
    },
    economics: {
      typicalPricePerQuintal: 2150,
      mspPricePerQuintal: 2090,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 27950,
      expectedNetProfitPerAcre: 17950,
      roi: 1.8,
    },
    riskFactors: ["Fall Armyworm infestation", "Waterlogging during seedling stage", "Early post-monsoon drought"],
    pestsAndDiseases: ["Fall Armyworm (Spodoptera frugiperda)", "Stem Borer", "Turcicum Leaf Blight"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IIMR Ludhiana / CACP Kharif 2024",
      lastUpdated: "2024-06-15",
    },
  },
  {
    id: "CROP011",
    slug: "soybean",
    name: "Soybean",
    hindiName: "सोयाबीन",
    category: "Oilseed",
    season: "Kharif",
    durationDays: 100,
    waterRequirementMm: 600,
    waterLevel: "Medium",
    suitableSoils: ["Black soil", "Loam", "Clay loam"],
    tempRange: { min: 18, max: 32, idealMin: 24, idealMax: 28 },
    rainfallMm: { min: 500, max: 900, optimal: 650 },
    yield: { kgPerHa: 1500, quintalsPerAcre: 6.0 },
    costs: {
      seed: 1300,
      fertilizer: 1800,
      labor: 3200,
      irrigation: 800,
      other: 700,
      totalPerAcre: 7800,
      totalPerHa: 19500,
    },
    economics: {
      typicalPricePerQuintal: 4680,
      mspPricePerQuintal: 4600,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 28080,
      expectedNetProfitPerAcre: 20280,
      roi: 2.6,
    },
    riskFactors: ["Heavy moisture during harvesting", "Girdle beetle damage", "Yellow Mosaic Virus"],
    pestsAndDiseases: ["Girdle Beetle", "Semilooper", "Yellow Mosaic Virus"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IISR Indore / CACP 2024",
      lastUpdated: "2024-06-15",
    },
  },
  {
    id: "CROP016",
    slug: "cotton",
    name: "Cotton (Kapas)",
    hindiName: "कपास",
    category: "Cash Crop",
    season: "Kharif",
    durationDays: 180,
    waterRequirementMm: 700,
    waterLevel: "Medium",
    suitableSoils: ["Black soil", "Alluvial", "Deep loam"],
    tempRange: { min: 15, max: 40, idealMin: 25, idealMax: 32 },
    rainfallMm: { min: 500, max: 1000, optimal: 700 },
    yield: { kgPerHa: 550, quintalsPerAcre: 6.5 },
    costs: {
      seed: 2200,
      fertilizer: 4000,
      labor: 8000,
      irrigation: 2400,
      other: 1600,
      totalPerAcre: 18200,
      totalPerHa: 45500,
    },
    economics: {
      typicalPricePerQuintal: 6920,
      mspPricePerQuintal: 6620,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 44980,
      expectedNetProfitPerAcre: 26780,
      roi: 1.47,
    },
    riskFactors: ["Pink Bollworm resistance", "Whitefly outbreaks (Cotton Leaf Curl Virus)", "Price volatility"],
    pestsAndDiseases: ["Pink Bollworm (Pectinophora gossypiella)", "Whitefly", "Bacterial Blight"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-CICR Nagpur / CACP 2024",
      lastUpdated: "2024-06-15",
    },
  },
  {
    id: "CROP020",
    slug: "onion",
    name: "Onion (Pyaz)",
    hindiName: "प्याज",
    category: "Vegetable",
    season: "Rabi",
    durationDays: 120,
    waterRequirementMm: 450,
    waterLevel: "Medium",
    suitableSoils: ["Loam", "Sandy loam", "Alluvial"],
    tempRange: { min: 10, max: 32, idealMin: 13, idealMax: 25 },
    rainfallMm: { min: 350, max: 650, optimal: 450 },
    yield: { kgPerHa: 18000, quintalsPerAcre: 72.8 },
    costs: {
      seed: 3600,
      fertilizer: 4000,
      labor: 8800,
      irrigation: 2800,
      other: 1600,
      totalPerAcre: 20800,
      totalPerHa: 52000,
    },
    economics: {
      typicalPricePerQuintal: 2850,
      mspPricePerQuintal: null,
      mspEligible: false,
      expectedGrossRevenuePerAcre: 207480,
      expectedNetProfitPerAcre: 186680,
      roi: 8.97,
    },
    riskFactors: ["Extreme price crash / gluts", "Post-harvest storage rot", "Purple blotch disease"],
    pestsAndDiseases: ["Thrips (Thrips tabaci)", "Purple Blotch (Alternaria porri)", "Stemphylium Leaf Blight"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-DOGR Rajgurunagar / Agmarknet Lasalgaon 2024",
      lastUpdated: "2024-08-01",
    },
  },
  {
    id: "CROP019",
    slug: "potato",
    name: "Potato (Aloo)",
    hindiName: "आलू",
    category: "Vegetable",
    season: "Rabi",
    durationDays: 100,
    waterRequirementMm: 500,
    waterLevel: "Medium",
    suitableSoils: ["Sandy loam", "Alluvial", "Loam"],
    tempRange: { min: 10, max: 28, idealMin: 15, idealMax: 22 },
    rainfallMm: { min: 300, max: 600, optimal: 450 },
    yield: { kgPerHa: 22000, quintalsPerAcre: 89.0 },
    costs: {
      seed: 7200,
      fertilizer: 6000,
      labor: 8000,
      irrigation: 3200,
      other: 2000,
      totalPerAcre: 26400,
      totalPerHa: 66000,
    },
    economics: {
      typicalPricePerQuintal: 1450,
      mspPricePerQuintal: null,
      mspEligible: false,
      expectedGrossRevenuePerAcre: 129050,
      expectedNetProfitPerAcre: 102650,
      roi: 2.88,
    },
    riskFactors: ["Late blight during foggy cloudy periods", "Cold storage availability", "Seed tuber quality"],
    pestsAndDiseases: ["Late Blight (Phytophthora infestans)", "Early Blight", "Potato Tuber Moth"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-CPRI Shimla / NHB 2024",
      lastUpdated: "2024-08-01",
    },
  },
  {
    id: "CROP001",
    slug: "paddy",
    name: "Paddy / Rice (Dhan)",
    hindiName: "धान",
    category: "Cereal",
    season: "Kharif",
    durationDays: 130,
    waterRequirementMm: 1250,
    waterLevel: "High",
    suitableSoils: ["Clay loam", "Clay", "Alluvial"],
    tempRange: { min: 10, max: 40, idealMin: 20, idealMax: 35 },
    rainfallMm: { min: 900, max: 1800, optimal: 1200 },
    yield: { kgPerHa: 4200, quintalsPerAcre: 17.0 },
    costs: {
      seed: 1800,
      fertilizer: 3600,
      labor: 7200,
      irrigation: 2800,
      other: 1200,
      totalPerAcre: 16600,
      totalPerHa: 41500,
    },
    economics: {
      typicalPricePerQuintal: 2320,
      mspPricePerQuintal: 2300,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 39440,
      expectedNetProfitPerAcre: 22840,
      roi: 1.37,
    },
    riskFactors: ["Groundwater depletion in tube-well areas", "Blast & Brown Planthopper outbreaks", "High electricity costs"],
    pestsAndDiseases: ["Bacterial Leaf Blight", "Rice Blast (Magnaporthe oryzae)", "Brown Plant Hopper"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-NRRI Cuttack / CACP 2024",
      lastUpdated: "2024-06-15",
    },
  },
  {
    id: "CROP012",
    slug: "groundnut",
    name: "Groundnut (Mungfali)",
    hindiName: "मूंगफली",
    category: "Oilseed",
    season: "Kharif",
    durationDays: 110,
    waterRequirementMm: 550,
    waterLevel: "Medium",
    suitableSoils: ["Sandy loam", "Red sandy loam", "Loam"],
    tempRange: { min: 20, max: 35, idealMin: 25, idealMax: 30 },
    rainfallMm: { min: 450, max: 750, optimal: 550 },
    yield: { kgPerHa: 1900, quintalsPerAcre: 7.7 },
    costs: {
      seed: 1600,
      fertilizer: 2000,
      labor: 3800,
      irrigation: 1200,
      other: 800,
      totalPerAcre: 9400,
      totalPerHa: 23500,
    },
    economics: {
      typicalPricePerQuintal: 6380,
      mspPricePerQuintal: 6377,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 49126,
      expectedNetProfitPerAcre: 39726,
      roi: 3.22,
    },
    riskFactors: ["Tikka leaf spot during humid rains", "Soil crusting affecting peg penetration", "White grub"],
    pestsAndDiseases: ["Tikka Disease (Cercospora personata)", "White Grub", "Collar Rot"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-DGR Junagadh / CACP 2024",
      lastUpdated: "2024-06-15",
    },
  },
  {
    id: "CROP017",
    slug: "sugarcane",
    name: "Sugarcane (Ganna)",
    hindiName: "गन्ना",
    category: "Cash Crop",
    season: "Perennial",
    durationDays: 360,
    waterRequirementMm: 2000,
    waterLevel: "High",
    suitableSoils: ["Deep loam", "Alluvial", "Clay loam"],
    tempRange: { min: 18, max: 38, idealMin: 25, idealMax: 32 },
    rainfallMm: { min: 1200, max: 2500, optimal: 1500 },
    yield: { kgPerHa: 80000, quintalsPerAcre: 324.0 },
    costs: {
      seed: 3200,
      fertilizer: 7200,
      labor: 14000,
      irrigation: 6000,
      other: 3200,
      totalPerAcre: 33600,
      totalPerHa: 84000,
    },
    economics: {
      typicalPricePerQuintal: 340, // FRP per quintal
      mspPricePerQuintal: 340,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 110160,
      expectedNetProfitPerAcre: 76560,
      roi: 2.27,
    },
    riskFactors: ["Delayed mill payments", "High water & power consumption", "Red rot disease"],
    pestsAndDiseases: ["Red Rot (Colletotrichum falcatum)", "Early Shoot Borer", "Pyrilla"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IISR Lucknow / CACP FRP 2024-25",
      lastUpdated: "2024-08-01",
    },
  },
  {
    id: "CROP008",
    slug: "barley",
    name: "Barley (Jau)",
    hindiName: "जौ",
    category: "Cereal",
    season: "Rabi",
    durationDays: 115,
    waterRequirementMm: 250,
    waterLevel: "Low",
    suitableSoils: ["Sandy loam", "Loam", "Alluvial", "Saline"],
    tempRange: { min: 4, max: 30, idealMin: 12, idealMax: 22 },
    rainfallMm: { min: 200, max: 450, optimal: 300 },
    yield: { kgPerHa: 2800, quintalsPerAcre: 11.3 },
    costs: {
      seed: 1200,
      fertilizer: 2000,
      labor: 3000,
      irrigation: 1000,
      other: 1000,
      totalPerAcre: 8200,
      totalPerHa: 20500,
    },
    economics: {
      typicalPricePerQuintal: 1950,
      mspPricePerQuintal: 1850,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 22035,
      expectedNetProfitPerAcre: 13835,
      roi: 1.69,
    },
    riskFactors: ["Late-winter aphid infestation", "Lodging from high winds near harvest", "Salinity tolerance limits"],
    pestsAndDiseases: ["Covered Smut", "Corn Leaf Aphid", "Barley Stripe Rust"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IIWBR Karnal / CACP Rabi MSP 2024-25",
      lastUpdated: "2024-10-15",
    },
  },
  {
    id: "CROP009",
    slug: "lentil",
    name: "Lentil / Masoor (मसूर)",
    hindiName: "मसूर",
    category: "Pulse",
    season: "Rabi",
    durationDays: 110,
    waterRequirementMm: 280,
    waterLevel: "Low",
    suitableSoils: ["Loam", "Clay loam", "Alluvial", "Sandy loam"],
    tempRange: { min: 6, max: 30, idealMin: 15, idealMax: 24 },
    rainfallMm: { min: 200, max: 450, optimal: 320 },
    yield: { kgPerHa: 1100, quintalsPerAcre: 4.5 },
    costs: {
      seed: 1400,
      fertilizer: 1500,
      labor: 2800,
      irrigation: 900,
      other: 800,
      totalPerAcre: 7400,
      totalPerHa: 18500,
    },
    economics: {
      typicalPricePerQuintal: 6500,
      mspPricePerQuintal: 6425,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 29250,
      expectedNetProfitPerAcre: 21850,
      roi: 2.95,
    },
    riskFactors: ["Rust during foggy weather", "Excessive moisture causing root rot", "Pod borer in early podding"],
    pestsAndDiseases: ["Lentil Rust (Uromyces viciae-fabae)", "Fusarium Wilt", "Pod Borer"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IIPR Kanpur / CACP Rabi MSP 2024-25",
      lastUpdated: "2024-10-15",
    },
  },
  {
    id: "CROP021",
    slug: "tomato",
    name: "Tomato (Tamatar)",
    hindiName: "टमाटर",
    category: "Vegetable",
    season: "Rabi",
    durationDays: 100,
    waterRequirementMm: 450,
    waterLevel: "Medium",
    suitableSoils: ["Loam", "Sandy loam", "Alluvial"],
    tempRange: { min: 10, max: 32, idealMin: 18, idealMax: 27 },
    rainfallMm: { min: 300, max: 650, optimal: 450 },
    yield: { kgPerHa: 25000, quintalsPerAcre: 101.2 },
    costs: {
      seed: 4500,
      fertilizer: 5000,
      labor: 8500,
      irrigation: 3200,
      other: 2280,
      totalPerAcre: 23480,
      totalPerHa: 58000,
    },
    economics: {
      typicalPricePerQuintal: 1800,
      mspPricePerQuintal: null,
      mspEligible: false,
      expectedGrossRevenuePerAcre: 182160,
      expectedNetProfitPerAcre: 158680,
      roi: 6.75,
    },
    riskFactors: ["Early blight and leaf curl virus", "Extreme price volatility in peak harvest", "Post-harvest perishability"],
    pestsAndDiseases: ["Fruit Borer (Helicoverpa)", "Early Blight", "Tomato Leaf Curl Virus"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IIHR Bengaluru / Agmarknet 2024",
      lastUpdated: "2024-08-01",
    },
  },
  {
    id: "CROP014",
    slug: "sunflower",
    name: "Sunflower (Surajmukhi)",
    hindiName: "सूरजमुखी",
    category: "Oilseed",
    season: "Rabi",
    durationDays: 100,
    waterRequirementMm: 500,
    waterLevel: "Medium",
    suitableSoils: ["Loam", "Black soil", "Alluvial"],
    tempRange: { min: 15, max: 34, idealMin: 20, idealMax: 28 },
    rainfallMm: { min: 350, max: 650, optimal: 450 },
    yield: { kgPerHa: 1200, quintalsPerAcre: 4.9 },
    costs: {
      seed: 1200,
      fertilizer: 2200,
      labor: 3000,
      irrigation: 1200,
      other: 740,
      totalPerAcre: 8340,
      totalPerHa: 20600,
    },
    economics: {
      typicalPricePerQuintal: 6760,
      mspPricePerQuintal: 6760,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 33124,
      expectedNetProfitPerAcre: 24784,
      roi: 2.97,
    },
    riskFactors: ["Bird damage near maturity", "Alternaria leaf spot", "Head rot during humid rains"],
    pestsAndDiseases: ["Helicoverpa head borer", "Alternaria Blight", "Rust"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IIOR Hyderabad / CACP 2024-25",
      lastUpdated: "2024-10-15",
    },
  },
  {
    id: "CROP005",
    slug: "pearl-millet",
    name: "Pearl Millet (Bajra)",
    hindiName: "बाजरा",
    category: "Cereal",
    season: "Kharif",
    durationDays: 90,
    waterRequirementMm: 400,
    waterLevel: "Low",
    suitableSoils: ["Sandy loam", "Sandy soil", "Loam"],
    tempRange: { min: 15, max: 42, idealMin: 25, idealMax: 33 },
    rainfallMm: { min: 250, max: 600, optimal: 380 },
    yield: { kgPerHa: 1600, quintalsPerAcre: 6.5 },
    costs: {
      seed: 700,
      fertilizer: 1400,
      labor: 1900,
      irrigation: 500,
      other: 520,
      totalPerAcre: 5020,
      totalPerHa: 12400,
    },
    economics: {
      typicalPricePerQuintal: 2625,
      mspPricePerQuintal: 2500,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 17062,
      expectedNetProfitPerAcre: 12042,
      roi: 2.4,
    },
    riskFactors: ["Ergot and downy mildew during overcast flowering", "Terminal drought in grain filling"],
    pestsAndDiseases: ["Downy Mildew (Green Ear)", "Ergot", "Shoot Fly"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-AICRP Pearl Millet / CACP Kharif 2024",
      lastUpdated: "2024-06-15",
    },
  },
  {
    id: "CROP004",
    slug: "sorghum",
    name: "Sorghum (Jowar)",
    hindiName: "ज्वार",
    category: "Cereal",
    season: "Kharif",
    durationDays: 110,
    waterRequirementMm: 450,
    waterLevel: "Low",
    suitableSoils: ["Black soil", "Clay loam", "Loam"],
    tempRange: { min: 15, max: 38, idealMin: 26, idealMax: 33 },
    rainfallMm: { min: 350, max: 700, optimal: 450 },
    yield: { kgPerHa: 1400, quintalsPerAcre: 5.7 },
    costs: {
      seed: 800,
      fertilizer: 1600,
      labor: 2400,
      irrigation: 600,
      other: 550,
      totalPerAcre: 5950,
      totalPerHa: 14700,
    },
    economics: {
      typicalPricePerQuintal: 3250,
      mspPricePerQuintal: 3180,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 18525,
      expectedNetProfitPerAcre: 12575,
      roi: 2.11,
    },
    riskFactors: ["Grain mold during untimely late rains", "Shoot fly in early vegetative phase"],
    pestsAndDiseases: ["Sorghum Shoot Fly", "Stem Borer", "Grain Mold"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IIMR Hyderabad / CACP Kharif 2024",
      lastUpdated: "2024-06-15",
    },
  },
  {
    id: "CROP008",
    slug: "pigeon-pea",
    name: "Pigeon Pea / Arhar (Tur)",
    hindiName: "अरहर / तूर",
    category: "Pulse",
    season: "Kharif",
    durationDays: 160,
    waterRequirementMm: 650,
    waterLevel: "Medium",
    suitableSoils: ["Loam", "Deep loam", "Black soil"],
    tempRange: { min: 18, max: 35, idealMin: 25, idealMax: 30 },
    rainfallMm: { min: 500, max: 900, optimal: 650 },
    yield: { kgPerHa: 900, quintalsPerAcre: 3.6 },
    costs: {
      seed: 1200,
      fertilizer: 1600,
      labor: 3100,
      irrigation: 800,
      other: 710,
      totalPerAcre: 7410,
      totalPerHa: 18300,
    },
    economics: {
      typicalPricePerQuintal: 7550,
      mspPricePerQuintal: 7000,
      mspEligible: true,
      expectedGrossRevenuePerAcre: 27180,
      expectedNetProfitPerAcre: 19770,
      roi: 2.67,
    },
    riskFactors: ["Pod borer outbreak during pod set", "Sterility Mosaic Disease", "Fusarium Wilt"],
    pestsAndDiseases: ["Gram Pod Borer", "Tur Pod Fly", "Fusarium Wilt"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IIPR Kanpur / CACP 2024",
      lastUpdated: "2024-06-15",
    },
  },
  {
    id: "CROP022",
    slug: "chili",
    name: "Chili (Mirch)",
    hindiName: "मिर्च",
    category: "Spice",
    season: "Kharif",
    durationDays: 150,
    waterRequirementMm: 600,
    waterLevel: "Medium",
    suitableSoils: ["Loam", "Black soil", "Red loam"],
    tempRange: { min: 15, max: 35, idealMin: 20, idealMax: 28 },
    rainfallMm: { min: 450, max: 850, optimal: 600 },
    yield: { kgPerHa: 1800, quintalsPerAcre: 7.3 },
    costs: {
      seed: 2800,
      fertilizer: 4500,
      labor: 9500,
      irrigation: 2500,
      other: 1750,
      totalPerAcre: 21050,
      totalPerHa: 52000,
    },
    economics: {
      typicalPricePerQuintal: 16500,
      mspPricePerQuintal: null,
      mspEligible: false,
      expectedGrossRevenuePerAcre: 120450,
      expectedNetProfitPerAcre: 99400,
      roi: 4.72,
    },
    riskFactors: ["Thrips and mite leaf curl complex", "Anthracnose dieback during high humidity"],
    pestsAndDiseases: ["Chili Thrips (Scirtothrips dorsalis)", "Anthracnose (Fruit Rot)", "Murda Leaf Curl"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IIHR Bengaluru / Guntur Spices Board 2024",
      lastUpdated: "2024-08-01",
    },
  },
  {
    id: "CROP023",
    slug: "turmeric",
    name: "Turmeric (Haldi)",
    hindiName: "हल्दी",
    category: "Spice",
    season: "Kharif",
    durationDays: 270,
    waterRequirementMm: 1400,
    waterLevel: "High",
    suitableSoils: ["Loam", "Clay loam", "Alluvial"],
    tempRange: { min: 18, max: 35, idealMin: 20, idealMax: 30 },
    rainfallMm: { min: 1000, max: 2000, optimal: 1400 },
    yield: { kgPerHa: 5500, quintalsPerAcre: 22.3 },
    costs: {
      seed: 10000,
      fertilizer: 8000,
      labor: 15000,
      irrigation: 4500,
      other: 2980,
      totalPerAcre: 40480,
      totalPerHa: 100000,
    },
    economics: {
      typicalPricePerQuintal: 12800,
      mspPricePerQuintal: null,
      mspEligible: false,
      expectedGrossRevenuePerAcre: 285440,
      expectedNetProfitPerAcre: 244960,
      roi: 6.05,
    },
    riskFactors: ["Rhizome rot in waterlogged soils", "High upfront seed rhizome cost", "Long 9-month crop duration"],
    pestsAndDiseases: ["Rhizome Rot (Pythium)", "Shoot Borer", "Leaf Spot"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-IISR Kozhikode / Nizamabad Mandi 2024",
      lastUpdated: "2024-08-01",
    },
  },
  {
    id: "CROP024",
    slug: "banana",
    name: "Banana (Kela)",
    hindiName: "केला",
    category: "Fruit",
    season: "Perennial",
    durationDays: 330,
    waterRequirementMm: 1800,
    waterLevel: "High",
    suitableSoils: ["Deep loam", "Alluvial", "Clay loam"],
    tempRange: { min: 15, max: 35, idealMin: 25, idealMax: 30 },
    rainfallMm: { min: 1200, max: 2200, optimal: 1800 },
    yield: { kgPerHa: 40000, quintalsPerAcre: 162.0 },
    costs: {
      seed: 14000,
      fertilizer: 12000,
      labor: 18000,
      irrigation: 8000,
      other: 4670,
      totalPerAcre: 56670,
      totalPerHa: 140000,
    },
    economics: {
      typicalPricePerQuintal: 2100,
      mspPricePerQuintal: null,
      mspEligible: false,
      expectedGrossRevenuePerAcre: 340200,
      expectedNetProfitPerAcre: 283530,
      roi: 5.0,
    },
    riskFactors: ["High wind lodging during bunching", "Panama wilt (Fusarium Tropical Race 4)", "Heavy irrigation requirement"],
    pestsAndDiseases: ["Panama Wilt", "Sigatoka Leaf Spot", "Banana Bunchy Top Virus"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-NRC Banana Tiruchirappalli / Jalgaon Mandi 2024",
      lastUpdated: "2024-08-01",
    },
  },
  {
    id: "CROP025",
    slug: "mango",
    name: "Mango (Aam)",
    hindiName: "आम",
    category: "Fruit",
    season: "Perennial",
    durationDays: 365,
    waterRequirementMm: 900,
    waterLevel: "Medium",
    suitableSoils: ["Deep loam", "Alluvial", "Red loam"],
    tempRange: { min: 10, max: 40, idealMin: 24, idealMax: 30 },
    rainfallMm: { min: 700, max: 1500, optimal: 1000 },
    yield: { kgPerHa: 8000, quintalsPerAcre: 32.4 },
    costs: {
      seed: 0,
      fertilizer: 3500,
      labor: 5500,
      irrigation: 2000,
      other: 1550,
      totalPerAcre: 12550,
      totalPerHa: 31000,
    },
    economics: {
      typicalPricePerQuintal: 3600,
      mspPricePerQuintal: null,
      mspEligible: false,
      expectedGrossRevenuePerAcre: 116640,
      expectedNetProfitPerAcre: 104090,
      roi: 8.29,
    },
    riskFactors: ["Alternate bearing cycles", "Fruit fly and powdery mildew during flowering", "Hailstorm damage"],
    pestsAndDiseases: ["Mango Hopper", "Powdery Mildew", "Oriental Fruit Fly"],
    provenance: {
      sourceType: "official",
      benchmarkSource: "ICAR-CISH Lucknow / Agmarknet 2024",
      lastUpdated: "2024-08-01",
    },
  },
];

